-- Run this in Supabase SQL Editor
-- ==============================================================================
-- TỔNG HỢP SQL KHỞI TẠO CƠ SỞ DỮ LIỆU CHUẨN CHO FUJIRISE (CUSTOM AUTH)
-- ==============================================================================

create extension if not exists "pgcrypto";

-- 1. BẢNG ADMINS (QUẢN TRỊ VIÊN)
drop table if exists public.admins;
CREATE TABLE public.admins (
    id text primary key, 
    email text unique not null, 
    password text not null, 
    role text not null, 
    phone text
);
INSERT INTO public.admins (id, email, password, role, phone) VALUES ('admin-1', 'admin@fujirise.com', 'Fujirise2026@', 'admin', '0868822210') ON CONFLICT (email) DO NOTHING;

-- 2. BẢNG SITE_SETTINGS (CẤU HÌNH GIAO DIỆN)
CREATE TABLE IF NOT EXISTS public.site_settings (id text primary key);
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS company_name text, ADD COLUMN IF NOT EXISTS hotline text, ADD COLUMN IF NOT EXISTS email text, ADD COLUMN IF NOT EXISTS address text, ADD COLUMN IF NOT EXISTS primary_color text, ADD COLUMN IF NOT EXISTS accent_color text, ADD COLUMN IF NOT EXISTS font_family text, ADD COLUMN IF NOT EXISTS interior_configs jsonb, ADD COLUMN IF NOT EXISTS warranty_policies jsonb, ADD COLUMN IF NOT EXISTS social_links jsonb, ADD COLUMN IF NOT EXISTS logo_url text, ADD COLUMN IF NOT EXISTS favicon_url text, ADD COLUMN IF NOT EXISTS hero_bg text, ADD COLUMN IF NOT EXISTS about_bg text;
INSERT INTO public.site_settings (id) VALUES ('default') ON CONFLICT DO NOTHING;

-- BẢNG PRIVATE_SETTINGS (CẤU HÌNH BẢO MẬT - TELEGRAM)
CREATE TABLE IF NOT EXISTS public.private_settings (
    id text primary key, telegram_token text, telegram_chat_id text, report_time text default '17:00'
);
INSERT INTO public.private_settings (id) VALUES ('default') ON CONFLICT DO NOTHING;

-- 3. BẢNG PRODUCTS (SẢN PHẨM)
CREATE TABLE IF NOT EXISTS public.products (
    id bigint generated by default as identity primary key, 
    title text not null, category text, description text, 
    images jsonb, specs jsonb, material text, "longDescription" text, 
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. BẢNG LEADS (KHÁCH HÀNG LIÊN HỆ & TUYỂN DỤNG)
CREATE TABLE IF NOT EXISTS public.leads (
    id uuid default gen_random_uuid() primary key,
    name text, phone text, email text, message text, category text, position text, years_experience text, expected_salary text, skills text, education text, portfolio text, resume_link text, cover_letter text, status text default 'new',
    created_at timestamptz default now()
);

-- 5. BẢNG PAGE_VIEWS (THỐNG KÊ TRUY CẬP)
CREATE TABLE IF NOT EXISTS public.page_views (
    id bigint generated by default as identity primary key, 
    path text, 
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. PHÂN QUYỀN RLS (CHO PHÉP TRUY CẬP TỪ CLIENT)
ALTER TABLE public.admins DISABLE ROW LEVEL SECURITY; ALTER TABLE public.site_settings DISABLE ROW LEVEL SECURITY; ALTER TABLE public.private_settings DISABLE ROW LEVEL SECURITY; ALTER TABLE public.products DISABLE ROW LEVEL SECURITY; ALTER TABLE public.leads DISABLE ROW LEVEL SECURITY; ALTER TABLE public.page_views DISABLE ROW LEVEL SECURITY;

-- 7. CẤU HÌNH BỘ NHỚ LƯU TRỮ ẢNH (STORAGE)
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true) ON CONFLICT (id) DO UPDATE SET public = true; DROP POLICY IF EXISTS "Public_Access" ON storage.objects; DROP POLICY IF EXISTS "Allow_Uploads" ON storage.objects; CREATE POLICY "Public_Access" ON storage.objects FOR SELECT USING (bucket_id = 'images'); CREATE POLICY "Allow_Uploads" ON storage.objects FOR ALL USING (bucket_id = 'images') WITH CHECK (bucket_id = 'images');
